<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login_Home</name>
   <tag></tag>
   <elementGuidId>6aed4a48-f3ea-4ee8-b842-1b16bbe75e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[3]/div/div/a/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6808c2b4-9856-4c4e-a3fc-0215b8fceeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:shadow-sm border-2 border-solid rounded text-base font-semibold primary</value>
      <webElementGuid>ea706dcc-66e2-4de1-9b38-a391e5d1251e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>a7430cd4-52db-4509-93ce-23ff81abf711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;w-full bg-[#FFFCE8] h-fit px-[84px] py-4 mb-6 flex&quot;]/div[@class=&quot;w-[1272px] h-full grid grid-cols-12 gap-x-6 items-center m-auto&quot;]/div[@class=&quot;col-span-3 h-full&quot;]/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;flex flex-row-reverse gap-4&quot;]/a[1]/button[@class=&quot;hover:shadow-sm border-2 border-solid rounded text-base font-semibold primary&quot;]</value>
      <webElementGuid>15cabf68-bb59-4091-898d-f41984ad4f13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div/div/a/button</value>
      <webElementGuid>70cfce9a-1ae5-44ee-8c06-411ff0a5f4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::button[1]</value>
      <webElementGuid>2bb0ddf2-a718-4d87-aff9-db703c9bc80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories'])[1]/preceding::button[2]</value>
      <webElementGuid>496ca10b-16a7-43f8-b09a-25f3de8c27c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>ef90941f-31d0-455a-9eeb-5d122fe88649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>41130be1-0407-4960-a368-5d08d185c4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>5fffff24-e4d2-44c4-840c-8ab76e6e410b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
