<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lets Connect Through The Questions_input-form</name>
   <tag></tag>
   <elementGuidId>3f7b44c7-bcd0-4715-91ab-006528f791de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c8066ee-2119-4ac9-8a37-7617c0d257fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>cf8a8dc7-11fc-4d47-bd45-ea7797a6588c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-form</value>
      <webElementGuid>5ec94e29-81d7-46ba-a88e-89dba352396a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;h-screen flex flex-row items-center&quot;]/div[@class=&quot;max-w-default mx-auto my-auto grid grid-cols-12 gap-x-6 flex flex-row&quot;]/div[@class=&quot;col-span-4 col-start-9 flex flex-col items-center&quot;]/div[@class=&quot;container flex flex-col&quot;]/div[@class=&quot;input-container flex flex-col content-stretch&quot;]/input[@class=&quot;input-form&quot;]</value>
      <webElementGuid>cdece4c2-756c-43a9-9a32-512084cdc364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='email']</value>
      <webElementGuid>841e3f8c-d9d4-4787-8c24-a636ac1566c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/input</value>
      <webElementGuid>2de3a13a-2945-4138-a13d-e52226874564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3e0a92d6-9e8b-4ecf-b404-a7271f08af0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email']</value>
      <webElementGuid>26478bfa-0717-4f3f-8e05-7d9c21b9ab73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
