<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_form_email</name>
   <tag></tag>
   <elementGuidId>4eb6f01d-3cc4-43e9-834e-150050c788ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1175cb36-dd25-4347-9f16-5a66f2f9af62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c91aa0b4-b150-43b1-a412-a0a31cbd6225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-form</value>
      <webElementGuid>63ada2c5-d4e9-475a-8cfc-551e8498b63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;h-screen flex flex-row items-center&quot;]/div[@class=&quot;max-w-default mx-auto my-auto grid grid-cols-12 gap-x-6 flex flex-row&quot;]/div[@class=&quot;col-span-4 col-start-9 flex flex-col items-center&quot;]/div[@class=&quot;container flex flex-col&quot;]/div[@class=&quot;input-container flex flex-col content-stretch&quot;]/input[@class=&quot;input-form&quot;]</value>
      <webElementGuid>62afc748-caaf-4914-954b-641d804341f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='email']</value>
      <webElementGuid>5c9aba66-215b-44f8-a45e-f582953f1cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/input</value>
      <webElementGuid>a42981b7-bb5b-4689-98c4-90f6f50cbd63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>55417484-e8a7-4ae0-a5eb-05f39db6ea95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email']</value>
      <webElementGuid>d86c482c-296a-48ed-ba94-52927d545619</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
