<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_search-bar w-full shadow-sm bg-white rounded border-2 border-black</name>
   <tag></tag>
   <elementGuidId>fbafe027-bee5-4a1a-8208-d22007372725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.search-bar.w-full.shadow-sm.bg-white.rounded.border-2.border-black</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>164a1399-7391-4a07-acc7-4e41855dddb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-bar w-full shadow-sm bg-white rounded border-2 border-black</value>
      <webElementGuid>d85b11d1-6e17-482e-8537-7209ab6b295a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search a question</value>
      <webElementGuid>4ac61055-29b9-4ae1-84d7-8d46af45616f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;w-full bg-[#FFFCE8] h-fit px-[84px] py-4 mb-6 flex&quot;]/div[@class=&quot;w-[1272px] h-full grid grid-cols-12 gap-x-6 items-center m-auto&quot;]/div[@class=&quot;col-span-7&quot;]/div[@class=&quot;container relative flex flex-row items-start text-base font-normal&quot;]/input[@class=&quot;search-bar w-full shadow-sm bg-white rounded border-2 border-black&quot;]</value>
      <webElementGuid>2917ad2d-3a27-4ab2-bff1-ee7c379eea73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/input</value>
      <webElementGuid>4664e2e0-d3ed-4891-8a9a-7bf7079a0193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>78b233bc-a748-422d-8d56-1ad67ba7e2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search a question']</value>
      <webElementGuid>b443c1d4-3d77-4591-8db1-2c3f44aa9460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
